micronaut:
  application:
    name: keymanagerRest

grpc:
  client:
    plaintext: true
    max-retry-attempts: 10
  channels:
    keyManager:
      address: '${GRPC_CLIENT:`localhost:50051`}'#'host.docker.internal:50051'
      plaintext: true
      max-retry-attempts: 5

jackson:
  serialization:
    writeDatesAsTimestamps: false